import { proxy } from "valtio";

const state = proxy({
  intro: true,
  color: "#EFBD48",
  isFrontLogoTexture: true,
  isBackLogoTexture: true,
  isFrontText: true,
  isFrontText1: true,

  isBackText: true,
  isFullTexture: false,
  frontLogoDecal: "./threejs.png",
  fullDecal: "./texture.jpeg",
  frontLogoPosition: [0, 0.04, 0.15],
  frontLogoScale: 0.15,
  backLogoDecal: "./threejs.png",
  backLogoPosition: [0, 0.04, -0.15],
  backLogoRotation: [0, Math.PI, 0],
  backLogoScale: 0.15,
  frontText: "Front Text",
  frontTextPosition: [0, -0.07, 0.15],
  frontTextRotation: [0, 0, 0],
  frontTextFontSize: 1,
  frontTextScale: [0.2, 0.04, 0.1],
  frontTextFont: "Arial",
  frontTextSize: 150,
  frontTextColor: "black",
  frontText1: "Front Text",
  frontTextPosition1: [0, 0.12, 0.15],
  frontTextRotation1: [0, 0, 0],
  frontTextFontSize1: 1,
  frontTextScale1: [0.2, 0.04, 0.1],
  frontTextFont1: "Arial",
  frontTextSize1: 150,
  frontTextColor1: "black",
  backText: "Back Text",
  backText1: "Back Text",
  backTextPosition: [0, -0.07, -0.15],
  backTextRotation: [0, Math.PI, 0],
  backTextFontSize: 0.1,
  backTextScale: [0.15, 0.07, 0.1],
  backTextFont: "Arial",
  backTextSize: 64,
  backTextColor: "white",
});

export default state;
